\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 1} 策略迭代}{14}{myalgorithm.1}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 2} 值迭代}{15}{myalgorithm.2}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 3} MC-On-policy（first visit）}{17}{myalgorithm.3}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 4} MC-Off-policy（every visit）}{18}{myalgorithm.4}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 5} TD($ 0 $)}{20}{myalgorithm.5}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 6} Sarsa（TD-on-policy）}{21}{myalgorithm.6}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 7} Q-learning（TD-off-policy）}{22}{myalgorithm.7}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 8} 双Q-learning}{22}{myalgorithm.8}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 9} n-TD}{23}{myalgorithm.9}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 10} n-Sarsa}{24}{myalgorithm.10}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 11} n-期望Sarsa-off-policy}{25}{myalgorithm.11}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 12} 梯度MC}{29}{myalgorithm.12}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 13} 半梯度TD($ 0 $)}{29}{myalgorithm.13}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 14} DQN}{31}{myalgorithm.14}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 15} REINFORCE}{34}{myalgorithm.15}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 16} QAC}{34}{myalgorithm.16}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 17} A2C}{35}{myalgorithm.17}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 18} off-policy Actor-Critic}{36}{myalgorithm.18}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 19} PPO}{37}{myalgorithm.19}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 20} DPG}{38}{myalgorithm.20}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 21} DDPG}{39}{myalgorithm.21}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 22} MADDPG}{42}{myalgorithm.22}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 23} n-树回溯}{45}{myalgorithm.23}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 24} n-Q($ \sigma $)-off-policy}{46}{myalgorithm.24}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 25} Dyna-Q}{47}{myalgorithm.25}%
\contentsline {myalgorithm}{\makebox [4em][l]{算法\hspace {0.25em plus 0.125em minus 0.08em}\ignorespaces 26} 确定性环境下的优先遍历}{48}{myalgorithm.26}%
\providecommand \tocbasic@end@toc@file {}\tocbasic@end@toc@file 
